name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Disable Google Services for CI
        run: |
          if [ -f app/build.gradle ]; then
            sed -i '/com.google.gms.google-services/d' app/build.gradle
            sed -i '/com.google.firebase/d' app/build.gradle
          fi

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Find APK
        if: success()
        run: find . -type f -name "*.apk"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/outputs/apk/debug/*.apk"